MvcKutuphane/Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class DuyuruController : Controller
    {
        DbKutuphaneEntities db = new DbKutuphaneEntities();
        // GET: Duyuru
        public ActionResult Index()
        {
            var duyuru = db.TblDuyurular.ToList();
            return View(duyuru); 
        }
        [HttpGet]
        public ActionResult DuyuruEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DuyuruEkle(TblDuyurular dyr)
        {
            db.TblDuyurular.Add(dyr);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruSil(int id)
        {
            var duyuru = db.TblDuyurular.Find(id);
            db.TblDuyurular.Remove(duyuru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruGetir(int id)
        {
            var duyuru = db.TblDuyurular.Find(id);
            return View("DuyuruGetir",duyuru);
        }
        public ActionResult DuyuruGuncelle(TblDuyurular dyr)
        {
            var duyuru = db.TblDuyurular.Find(dyr.ID);
            duyuru.KATEGORI = dyr.KATEGORI;
            duyuru.ICERİK = dyr.ICERİK;
            duyuru.TARIH = DateTime.Parse(DateTime.Now.ToShortDateString());
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Duyuru/DuyuruEkle.cshtml
@model MvcKutuphane.Models.Entity.TblDuyurular
@{
    ViewBag.Title = "DuyuruEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div style="margin-bottom:15px"></div>
    <div style="margin-bottom:15px">
        <label>Duyuru Kategori</label>
        @Html.TextBoxFor(x => x.KATEGORI, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        <label>İçerik</label>
        @Html.TextAreaFor(x => x.ICERİK, new { @class = "form-control" })
    </div>
    <input type="text" class="form-control" name="TARIH" value="@DateTime.Now.ToShortDateString()" />
    <br />
    <button class="btn btn-info">Duyuru Ekle</button>
</form>

MvcKutuphane/Views/Duyuru/DuyuruGetir.cshtml
@model MvcKutuphane.Models.Entity.TblDuyurular

@{
    ViewBag.Title = "DuyuruGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <div>
            <label>Duyuru ID</label>
            @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
            <br />
            <label>Kategori</label>
            @Html.TextBoxFor(x => x.KATEGORI, new { @class = "form-control" })
            <br />
            <label>İçerik</label>
            @Html.TextBoxFor(x => x.ICERİK, new { @class = "form-control" })
            <br />
            <label>Tarih</label>
            @Html.TextBoxFor(x => x.TARIH, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <br />
        <button class="btn btn-info">Duyuru Güncelle</button>
    </div>
}

MvcKutuphane/Views/Duyuru/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TblDuyurular>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
    string renk = "";
}

<h2>Duyurular</h2>

<table class="table table-bordered">
    <tr>
        <th>Duyuru Id</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>İçerik</th>
    </tr>
    @foreach (var ktg in Model)
    {
        if (ktg.KATEGORI == "Kitaplarimizz")
        {
            renk = "bg-info text-white";
        }
        if (ktg.KATEGORI == "deneme")
        {
            renk = "bg-warning text-white";
        }
        if (ktg.KATEGORI == "Diger")
        {
            renk = "bg-success text-white";
        }
        if (ktg.KATEGORI == "Istek Kutusu")
        {
            renk = "bg-danger text-white";
        }
        <tr class="@renk">
            <td>@ktg.ID</td>
            <td>@ktg.KATEGORI</td>
            <td>@Convert.ToDateTime(ktg.TARIH).ToShortDateString()</td>
            <td><a href="/Duyuru/DuyuruSil/@ktg.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Duyuru/DuyuruGetir/@ktg.ID" class="btn btn-info">Detay</a></td>
        </tr>
    }
</table>
<a href="/Duyuru/DuyuruEkle/" class="btn btn-primary">Yeni Duyuru</a>